### PR TITLE
Bump dependencies in composer.lock as at 201811025

### PR DESCRIPTION
**Pull request by phil-davis**
@PVince81 @DeepDiver1975  Do we need to do this any more?

(see PR #15  )

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I'd go for #14 - but lets chat once @patrickjahns is back

**Comment by phil-davis** [comment]
Yes, there is no rush for this!

**Comment by patrickjahns** [comment]
I'd opt for #14 / #15 - would require to touch every repository once to get php-cs-fixer integrated again. Open for creating a PR and polishing up the rest in the next days

**Comment by DeepDiver1975** [comment]
>  would require to touch every repository once to get php-cs-fixer integrated again. Open for creating a PR and polishing up the rest in the next days

Before we do so I'd like to bring up the idea to use tooly instead of composer-bin. see https://github.com/owncloud/announcementcenter/pull/97#issuecomment-434216782

Pro on tooly:
- phars are used - phar is the first choice for using any of these tools (cs-fixer, phan, phpstan)
- phars live in composer/bin - no different path then with composer-bin
- one composer install pulls in all tools - no additional calls in all composer bin paths

Con:
- no autoload of php-cs config class - we need to explicit require

**Comment by patrickjahns** [comment]
@DeepDiver1975 
> Before we do so I'd like to bring up the idea to use tooly instead of composer-bin.

Remember that I was telling you about different options and composer-bin to be the choice for us ;-)
When researching about options for segregating (dependencies) of cli tools from composer - I've also had a look on tooly and decided against it.

Looking over your pro list - some remarks:
> phars are used - phar is the first choice for using any of these tools (cs-fixer, phan, phpstan)

Not all tools out there are offering phars, there are quite a few (static) code analysing tools that are not (yet) available as phar

> phars live in composer/bin - no different path then with composer-bin

Where is the upside of this? This disallows using two versions of the same phar, as the symlink can only point to one version. If required - composer-bin can also symlink the tool to the normal bin directory ref: https://github.com/bamarni/composer-bin-plugin#disable-links

> one composer install pulls in all tools - no additional calls in all composer bin paths

This can also be done with composer right now - but for timeout issues ( as composer-bin is a "sub-process") opted for not pulling in all tools at once


Reasons for using composer-bin instead of tooly:
- available for any package/tool that can be required via composer ( not reliant on the project providing a phar )
- ability to extend tools with custom packages (in this case our own coding-standard; Think about Behat which requires some extensions, they can be included in one namespace together and do not pollute the root composer file )
- tooly requires explicit management of urls - with composer-bin we can use semver to automatically use the latest version of a tool

**Comment by phil-davis** [comment]
IMO not needed. See my comment https://github.com/owncloud/coding-standard/pull/15#issuecomment-462714584 - PR #15 is a better thing to do.

**Pull request closed without merging**
